export const FETCH_CONFIG_SECTION_REQUEST = 'FETCH_CONFIG_SECTION_REQUEST'
export const FETCH_CONFIG_SECTION_SUCCESS = 'FETCH_CONFIG_SECTION_SUCCESS'
export const FETCH_CONFIG_SECTION_FAILURE = 'FETCH_CONFIG_SECTION_FAILURE'

export const FETCH_CONFIG_BLOCK_REQUEST = 'FETCH_CONFIG_BLOCK_REQUEST'
export const FETCH_CONFIG_BLOCK_SUCCESS = 'FETCH_CONFIG_BLOCK_SUCCESS'
export const FETCH_CONFIG_BLOCK_FAILURE = 'FETCH_CONFIG_BLOCK_FAILURE'

export const FETCH_CONFIG_ANIMATION_REQUEST = 'FETCH_CONFIG_ANIMATION_REQUEST'
export const FETCH_CONFIG_ANIMATION_SUCCESS = 'FETCH_CONFIG_ANIMATION_SUCCESS'
export const FETCH_CONFIG_ANIMATION_FAILURE = 'FETCH_CONFIG_ANIMATION_FAILURE'
